image: nimlang/choosenim

build:
  stage: build
  script:
    - choosenim update devel
    - nim default --cc:gcc -o:"Nalwald-default" Nalwald.nim
    - nim debug --cc:gcc -o:"Nalwald-debug" Nalwald.nim
    - cd parameterOptimization/
    - nim c generatePositions.nim
    - nim c removeNonQuietPositions.nim
    - nim c mergeDuplicateAndSelect.nim
    - nim c labelPositions.nim
    - nim c optimization.nim
    - nim c calculatePieceValue.nim
  artifacts:
    paths:
      - Nalwald-default
      - Nalwald-debug

test:
  stage: test
  script:
    - echo -e "test 1000000\nquit\n" | ./Nalwald-debug
    - echo -e "test 10000000\nquit\n" | ./Nalwald-default
