image: nimlang/choosenim

build:
  stage: build
  script:
    - choosenim update devel
    - nim default --cc:gcc -o:"Nalwald-default" Nalwald.nim
    - nim debug --cc:gcc -o:"Nalwald-debug" Nalwald.nim
    - cd parameterOptimization/
    - nim c --cc:gcc generatePositions.nim
    - nim c --cc:gcc removeNonQuietPositions.nim
    - nim c --cc:gcc mergeDuplicateAndSelect.nim
    - nim c --cc:gcc labelPositions.nim
    - nim c --cc:gcc optimization.nim
    - nim c --cc:gcc calculatePieceValue.nim
    - nimble install taskpools@0.0.5
    - nim c --cc:gcc generateTrainingData.nim
  artifacts:
    paths:
      - Nalwald-default
      - Nalwald-debug

test:
  stage: test
  script:
    - echo -e "about\ntest 1000000\nquit\n" | ./Nalwald-debug
    - echo -e "about\ntest 10000000\nquit\n" | ./Nalwald-default
